Add release tag gh action (#1169)
Signed-off-by: Fiachra Corcoran <fiachra.corcoran@est.tech>

diff --git a/contrib/functions/go/Makefile b/contrib/functions/go/Makefile
--- a/contrib/functions/go/Makefile
+++ b/contrib/functions/go/Makefile
@@ -131,8 +131,14 @@ func-build: func-verify
 	../../../scripts/go-function-release.sh build contrib
 
 func-push:
-	@echo Pushing image $(CURRENT_FUNCTION)...
-	../../../scripts/go-function-release.sh push contrib
+	@echo "Checking if $(CURRENT_FUNCTION) is a valid listed function..."
+	@if echo "$(FUNCTIONS)" | grep -qw "$(CURRENT_FUNCTION)"; then \
+		echo "Pushing image $(CURRENT_FUNCTION)..."; \
+		../../../scripts/go-function-release.sh push contrib; \
+	else \
+		echo "Error: $(CURRENT_FUNCTION) is not a valid listed function!"; \
+		exit 1; \
+	fi
 
 docs-generate:
 	$(GOBIN)/mdtogo $(CURRENT_FUNCTION) $(CURRENT_FUNCTION)/generated --license=none --strategy=cmdDocs
diff --git a/functions/go/Makefile b/functions/go/Makefile
--- a/functions/go/Makefile
+++ b/functions/go/Makefile
@@ -154,8 +154,14 @@ func-build: func-verify
 	../../scripts/go-function-release.sh build curated
 
 func-push:
-	@echo Pushing image $(CURRENT_FUNCTION)...
-	../../scripts/go-function-release.sh push curated
+	@echo "Checking if $(CURRENT_FUNCTION) is a valid listed function..."
+	@if echo "$(FUNCTIONS)" | grep -qw "$(CURRENT_FUNCTION)"; then \
+		echo "Pushing image $(CURRENT_FUNCTION)..."; \
+		../../scripts/go-function-release.sh push curated; \
+	else \
+		echo "Error: $(CURRENT_FUNCTION) is not a valid listed function!"; \
+		exit 1; \
+	fi
 
 docs-generate:
 	$(GOBIN)/mdtogo $(CURRENT_FUNCTION) $(CURRENT_FUNCTION)/generated --license=none --strategy=cmdDocs
